name: Synchronize Thcrap Chinese branch patch file.
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0/6 * * *'
jobs:
  Download_latest_patch_file_and_save:
    runs-on: ubuntu-latest
    steps:
    - name: Preparing for push to GitHub and Coding repository.
      env:
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
          CODING_NAME: ${{ secrets.CODING_NAME }}
          GITHUB_TOKEN: ${{ secrets.SYNCHONIZE_TOKEN }}
      run: |
        git clone https://${CODING_NAME}:${CODING_TOKEN}@e.coding.net/thpatch-cn/thcrapcn/Thpatch_CN_Patchfiles_Mirror.git
        sudo rm -rf ./Thpatch_CN_Patchfiles_Mirror/aero ./Thpatch_CN_Patchfiles_Mirror/base_tasofro ./Thpatch_CN_Patchfiles_Mirror/base_tsa ./Thpatch_CN_Patchfiles_Mirror/lang_zh-hans
        git clone https://$GITHUB_TOKEN@github.com/ROCO-freedom/Thpatch_CN_Mirror.git
        git clone https://${CODING_NAME}:${CODING_TOKEN}@e.coding.net/thpatch-cn/thcrapcn/thcrap-tsa-CN-mirror.git
        sudo rm -rf ./thcrap-tsa-CN-mirror/aero ./thcrap-tsa-CN-mirror/base_tasofro ./thcrap-tsa-CN-mirror/base_tsa
    - name: Pull the latest patch file from the main source server (https://srv.thpatch.net/lang_zh-hans/)
      run: |
        cd ./Thpatch_CN_Mirror/TimingSync
        sudo wget -tries=10 https://srv.thpatch.net/lang_zh-hans/files.js
        sudo chmod +x ./PatchFileSync
        ./PatchFileSync repo_files.js files.js
        if [[ -d "lang_zh-hans" ]]; then
        sudo cp -frp ./lang_zh-hans/ ../
        sudo rm -rf ./lang_zh-hans
        fi
        sudo rm -f repo_files.js
        sudo mv files.js repo_files.js
            
    - name: Pull the latest hook config files from thcrap-tsa（https://github.com/thpatch/thcrap-tsa）
      run: |
        cd ./Thpatch_CN_Mirror
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/aero
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tasofro
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tsa
            
    - name: Regenerate the files.js for each folder.
      run: |
        # 生成前准备
        cd ./Thpatch_CN_Mirror/TimingSync
        sudo mkdir aero base_tasofro base_tsa
        sudo mv ../aero/.svn ./aero/.svn
        sudo mv ../base_tasofro/.svn ./base_tasofro/.svn
        sudo mv ../base_tsa/.svn ./base_tsa/.svn
        sudo cp repo_update ../repo_update
        sudo cp repo_update ../../thcrap-tsa-CN-mirror/repo_update
        # 生成files.js
        cd ..
        sudo rm -rf ./aero/files.js ./base_tasofro/files.js ./base_tsa/files.js ./lang_zh-hans/files.js
        sudo mv aero ../thcrap-tsa-CN-mirror/aero
        sudo mv base_tasofro ../thcrap-tsa-CN-mirror/base_tasofro
        sudo mv base_tsa ../thcrap-tsa-CN-mirror/base_tsa
        sudo chmod +x ./repo_update
        ./repo_update
        cd ../thcrap-tsa-CN-mirror
        sudo chmod +x ./repo_update
        ./repo_update
        # 清理并恢复目录结构
        sudo rm -f repo_update ../Thpatch_CN_Mirror/repo_update
        sudo mv aero ../Thpatch_CN_Mirror/aero
        sudo mv base_tasofro ../Thpatch_CN_Mirror/base_tasofro
        sudo mv base_tsa ../Thpatch_CN_Mirror/base_tsa
        cd ../Thpatch_CN_Mirror/TimingSync
        sudo mv ./aero/.svn ../aero/.svn
        sudo mv ./base_tasofro/.svn ../base_tasofro/.svn
        sudo mv ./base_tsa/.svn ../base_tsa/.svn
        sudo rm -rf aero base_tasofro base_tsa
        
    - name: Push the patch file to the GitHub repository.
      env:
          GITHUB_TOKEN: ${{ secrets.SYNCHONIZE_TOKEN }}
      run: |
        cd ./Thpatch_CN_Mirror
        git config --global user.name "ROCO2021"
        git config --global user.email "1401548627@qq.com" 
        git add .
        git status
        git commit -m $(echo -e "定时补丁文件更新。`date "+%Y-%m-%d===>%H:%M"`(UTC)") || true
        git push https://$GITHUB_TOKEN@github.com/ROCO-freedom/Thpatch_CN_Mirror.git || true
    
    - name: Push the latest file to Coding repository.
      env:
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
          CODING_NAME: ${{ secrets.CODING_NAME }}
      run: |
        # 移动文件到所属Coding仓库
        cd ./Thpatch_CN_Mirror
        sudo mv ./lang_zh-hans ../Thpatch_CN_Patchfiles_Mirror
        sudo mv ./aero ../thcrap-tsa-CN-mirror/aero
        sudo mv ./base_tasofro ../thcrap-tsa-CN-mirror/base_tasofro
        sudo mv ./base_tsa ../thcrap-tsa-CN-mirror/base_tsa
        git config --global user.name "ROCO2021"
        git config --global user.email "1401548627@qq.com" 
        # 提交lang_zh-hans仓库
        cd ../Thpatch_CN_Patchfiles_Mirror
        git add .
        git status
        git commit -m $(echo -e "同步至国内仓库。`date "+%Y-%m-%d===>%H:%M"`(UTC)") || true
        git push -f https://${CODING_NAME}:${CODING_TOKEN}@e.coding.net/thpatch-cn/thcrapcn/Thpatch_CN_Patchfiles_Mirror.git || true
        # 提交thcrap-tsa仓库
        cd ../thcrap-tsa-CN-mirror
        git add .
        git status
        git commit -m $(echo -e "同步至国内仓库。`date "+%Y-%m-%d===>%H:%M"`(UTC)") || true
        git push -f https://${CODING_NAME}:${CODING_TOKEN}@e.coding.net/thpatch-cn/thcrapcn/thcrap-tsa-CN-mirror.git || true
    - name: Clean the space.
      run: |
        sudo rm -rf *
